name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@main
              
            - name: Welcome message
              run: echo "My First Github Actions Job"

            - name: List Files
              run: ls

            - name: Read File
              run: cat readme.md
